set(CPACK_GENERATOR NSIS)

set(CPACK_PACKAGE_VENDOR              "LVWL")
set(CPACK_PACKAGE_NAME                "${PROJECT_NAME}")
set(CPACK_RESOURCE_FILE_LICENSE       "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README        "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_FILE_NAME           "${CPACK_PACKAGE_NAME}-setup")
set(CPACK_PACKAGE_INSTALL_DIRECTORY   "${CPACK_PACKAGE_VENDOR}\\\\${CPACK_PACKAGE_NAME}")
set(CPACK_PACKAGE_EXECUTABLES         "understory;UnderStory")

set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL  ON)
set(CPACK_NSIS_PACKAGE_NAME                    "${CPACK_PACKAGE_NAME}")
set(CPACK_NSIS_MUI_ICON                        "${CMAKE_CURRENT_SOURCE_DIR}/src/app/package/install.ico")
set(CPACK_NSIS_UNINSTALL_NAME                  "Uninstall ${CPACK_PACKAGE_NAME}")

include(CPack)