// This file is autogenerated by _understory.h with CMAKE
#define APP_NAME "${PROJECT_NAME}"
#define APP_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}"
#define APP_FULL_DENOM "${PROJECT_NAME} ${CMAKE_PROJECT_VERSION}"
