// UnderStory
// An intuitive Pen & Paper experience
// Copyright (C) 2020 Guillaume Vara

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Any graphical resources available within the source code may
// use a different license and copyright : please refer to their metadata
// for further details. Graphical resources without explicit references to a
// different license and copyright still refer to this GPL.

#pragma once

// This file is autogenerated by _understory.h with CMAKE
#define APP_NAME "UnderStory"
#define APP_CURRENT_VERSION "0.0.7"
#define APP_FULL_DENOM "UnderStory 0.0.7"
#define APP_REPOSITORY_HOST "dl.bintray.com"
#define APP_REPOSITORY_COMMAND "/amphaal/understory/repository/Updates.xml"
#define APP_TRANSLATION_FOLDER "translations"
#define SENTRY_ENDPOINT "https://b9618c02d38d4633b02c3dd2b736674e@o333337.ingest.sentry.io/5518788"
#define GITHUB_VERSION_NAME "understory@0.0.7"
