// UnderStory
// An intuitive Pen & Paper experience
// Copyright (C) 2020 Guillaume Vara

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// Any graphical resources available within the source code may
// use a different license and copyright : please refer to their metadata
// for further details. Graphical resources without explicit references to a
// different license and copyright still refer to this GPL.

#pragma once

// This file is autogenerated by _understory.h with CMAKE
#define APP_NAME "${PROJECT_NAME}"
#define APP_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}"
#define APP_FULL_DENOM "${PROJECT_NAME} ${CMAKE_PROJECT_VERSION}"
#define APP_REPOSITORY_HOST "${APP_REPOSITORY_HOST}"
#define APP_REPOSITORY_COMMAND "${APP_REPOSITORY_COMMAND}"
#define APP_TRANSLATION_FOLDER "${APP_TRANSLATION_FOLDER}"
#define SENTRY_ENDPOINT "${SENTRY_ENDPOINT}"
#define GITHUB_VERSION_NAME "${PROJECT_NAME_LOWER}@${CMAKE_PROJECT_VERSION}"